<!DOCTYPE HTML>
<!-- Website Template by freewebsitetemplates.com -->
<?php 
$templateURL = $this->basePath('/templates/hairstyle/');
?>
<html>
    <head>
        <meta charset="UTF-8">
        <title>ZiZurz Website Template</title>       
        <link rel="stylesheet" href="<?php echo $templateURL;?>css/style.css" type="text/css">
    </head>
    <body>
        <div id="header">
            <div class="section">
                <div class="logo">
                    <a href="index">zizurz</a>
                </div>
                <?php
                    require_once 'menu.php';
                ?>
            </div>
            <?php
            $layout = $this->layout()->getChildren();
            $template = $layout[0]->getTemplate();
            if ($template == 'template/index/index') {            
                require_once 'banner.php';
            }
            ?>
        </div>
        <?php echo $this->content; ?>
        <?php require_once 'footer.php'; ?>
    </body>
</html>