<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    //module là một mảng chứa tên 'namespaces' của các module trong ứng dụng
    'modules' => array(
        'Application',
        'Template',
        'Admin'
        ),
    // module_listener_options là một mảng chứa thông tin của Module 
   // Mảng này được đưa vào phần quản lý Module (ModuleManager)
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
            ),
        //config_glob_paths: là một mảng chứa các tập tin cấu hình của ứng dụng
        'config_glob_paths' => array('config/autoload/{,*.}{global,local}.php')
        )
    );
