<div id="body">
    <h3>hairstyles</h3>
    <ul>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle1.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle2.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle3.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle4.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle5.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle6.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle7.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle8.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle9.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle10.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle11.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle12.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle13.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle14.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle15.jpg" alt=""></a>
        </li>
        <li>
            <a href="#"><img src="<?php echo $this->basePath(); ?>/images/hairstyle16.jpg" alt=""></a>
        </li>
    </ul>
    <a href="#" class="more">show more</a>
</div>