<!DOCTYPE HTML>
<!-- Website Template by freewebsitetemplates.com -->
<html>
    <head>
        <meta charset="UTF-8">
        <title>Hairstyle - ZiZurz Website Template</title>
        <link rel="stylesheet" href="<?php echo $this->basePath(); ?>/css/style.css" type="text/css">
    </head>
    <body>
        <div id="header">
            <div class="section">
                <div class="logo">
                    <a href="index">zizurz</a>
                </div>
                <ul>
                    <li>
                        <a href="index">home</a>
                    </li>
                    <li>
                        <a href="about">about</a>
                    </li>
                    <li class="selected">
                        <a href="hairstyle">hairstyles</a>
                    </li>
                    <li>
                        <a href="news">news</a>
                    </li>
                    <li>
                        <a href="contact">contact</a>
                    </li>
                </ul>
            </div>
        </div>
        <div id="body">
            <h3>hairstyles</h3>
            <ul>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle1.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle2.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle3.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle4.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle5.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle6.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle7.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle8.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle9.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle10.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle11.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle12.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle13.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle14.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle15.jpg" alt=""></a>
                </li>
                <li>
                    <a href="#"><img src="<?php echo $this->basePath();?>/images/hairstyle16.jpg" alt=""></a>
                </li>
            </ul>
            <a href="#" class="more">show more</a>
        </div>
        <div id="footer">
            <div>
                <div class="connect">
                    <a href="http://freewebsitetemplates.com/go/twitter/" id="twitter">twitter</a>
                    <a href="http://freewebsitetemplates.com/go/facebook/" id="facebook">facebook</a>
                    <a href="http://freewebsitetemplates.com/go/googleplus/" id="googleplus">googleplus</a>
                    <a href="http://pinterest.com/fwtemplates/" id="pinterest">pinterest</a>
                </div>
                <p>
                    &copy; copyright 2023 | all rights reserved.
                </p>
            </div>
        </div>
    </body>
</html>