<h1>Them mot thanh vien moi</h1>
<?php
//Lấy đối tượng Admin\Form\UserForm từ trong VIEW ra
$form = $this->form;
$form->prepare();
?>

<!-- Tạo thẻ <form...> và các giá trị thuộc tính của thẻ này -->
<?php echo $this->form()->openTag($form); ?>
<ul>
    <li>
        <span><?php echo $this->formLabel($form->get('username')); ?></span>
        <?php echo $this->formElement($form->get('username')); ?>
    </li>
    <li>
        <span><?php echo $this->formLabel($form->get('picture')); ?></span>
        <?php echo $this->formElement($form->get('picture')); ?>
    </li>
    <li>
        <span><?php echo $this->formLabel($form->get('email')); ?></span>
        <?php echo $this->formElement($form->get('email')); ?>
    </li>
    <li>
        <span><?php echo $this->formLabel($form->get('password')); ?></span>
        <?php echo $this->formElement($form->get('password')); ?>
    </li>
    <li>
        <span><?php echo $this->formLabel($form->get('group')); ?></span>
        <?php echo $this->formElement($form->get('group')); ?>
    </li>      
    <li>
        <!--Tạo nút Submit -->
        <?php echo $this->formElement($form->get('submit')); ?>
    </li>
</ul>

<!-- Đóng thẻ </form> -->
<?php echo $this->form()->closeTag() ?>